import Navbar from '@components/Navbar';
import BackToTop from '@components/BackToTop';
import { Footer } from '@components/Footer';
import RootStyleRegistry from './Provider';
import Main from '@components/Main';
import { HeaderTabs } from '@components/TestNav';
import { user, headerTabData } from '@utils/mock';

export const metadata = {
  title: 'Anasayfa',
  description: 'Generated by Daktilo2.0',
};
export default function RootLayout({ children }) {
	return (
		<html lang="en">
				<RootStyleRegistry>
					<Navbar navType='nav1' />
          {/* <HeaderTabs user={user} tabs={headerTabData} /> */}
					<Main>
            {children}
            </Main>
					<Footer />
					<BackToTop />
				</RootStyleRegistry>
		</html>
	);
}

