import React from 'react';

export const metadata = {
  title: 'Yazarlar',
  description: 'Generated by Next.js',
};

export default function RootLayout({children}) {
  return (
    <div>
      {children}
    </div>
  )
};
