import React from 'react'

export const metadata = {
    title: 'Yazarlar',
    description: 'Generated by Next.js',
  }

function Authors() {
    return (
        <div>
            Yazarlar
        </div>
    )
}

export default Authors;
